/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysesAnalysisIdRouteRouteImport } from './routes/analyses/$analysisId/route'
import { Route as AnalysesAnalysisIdIndexRouteImport } from './routes/analyses/$analysisId/index'
import { Route as AnalysesAnalysisIdReviewsRouteImport } from './routes/analyses/$analysisId/reviews'
import { Route as AnalysesAnalysisIdClustersRouteImport } from './routes/analyses/$analysisId/clusters'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysesAnalysisIdRouteRoute = AnalysesAnalysisIdRouteRouteImport.update({
  id: '/analyses/$analysisId',
  path: '/analyses/$analysisId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysesAnalysisIdIndexRoute = AnalysesAnalysisIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalysesAnalysisIdRouteRoute,
} as any)
const AnalysesAnalysisIdReviewsRoute =
  AnalysesAnalysisIdReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AnalysesAnalysisIdRouteRoute,
  } as any)
const AnalysesAnalysisIdClustersRoute =
  AnalysesAnalysisIdClustersRouteImport.update({
    id: '/clusters',
    path: '/clusters',
    getParentRoute: () => AnalysesAnalysisIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyses/$analysisId': typeof AnalysesAnalysisIdRouteRouteWithChildren
  '/analyses/$analysisId/clusters': typeof AnalysesAnalysisIdClustersRoute
  '/analyses/$analysisId/reviews': typeof AnalysesAnalysisIdReviewsRoute
  '/analyses/$analysisId/': typeof AnalysesAnalysisIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyses/$analysisId/clusters': typeof AnalysesAnalysisIdClustersRoute
  '/analyses/$analysisId/reviews': typeof AnalysesAnalysisIdReviewsRoute
  '/analyses/$analysisId': typeof AnalysesAnalysisIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyses/$analysisId': typeof AnalysesAnalysisIdRouteRouteWithChildren
  '/analyses/$analysisId/clusters': typeof AnalysesAnalysisIdClustersRoute
  '/analyses/$analysisId/reviews': typeof AnalysesAnalysisIdReviewsRoute
  '/analyses/$analysisId/': typeof AnalysesAnalysisIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyses/$analysisId'
    | '/analyses/$analysisId/clusters'
    | '/analyses/$analysisId/reviews'
    | '/analyses/$analysisId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyses/$analysisId/clusters'
    | '/analyses/$analysisId/reviews'
    | '/analyses/$analysisId'
  id:
    | '__root__'
    | '/'
    | '/analyses/$analysisId'
    | '/analyses/$analysisId/clusters'
    | '/analyses/$analysisId/reviews'
    | '/analyses/$analysisId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysesAnalysisIdRouteRoute: typeof AnalysesAnalysisIdRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyses/$analysisId': {
      id: '/analyses/$analysisId'
      path: '/analyses/$analysisId'
      fullPath: '/analyses/$analysisId'
      preLoaderRoute: typeof AnalysesAnalysisIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyses/$analysisId/': {
      id: '/analyses/$analysisId/'
      path: '/'
      fullPath: '/analyses/$analysisId/'
      preLoaderRoute: typeof AnalysesAnalysisIdIndexRouteImport
      parentRoute: typeof AnalysesAnalysisIdRouteRoute
    }
    '/analyses/$analysisId/reviews': {
      id: '/analyses/$analysisId/reviews'
      path: '/reviews'
      fullPath: '/analyses/$analysisId/reviews'
      preLoaderRoute: typeof AnalysesAnalysisIdReviewsRouteImport
      parentRoute: typeof AnalysesAnalysisIdRouteRoute
    }
    '/analyses/$analysisId/clusters': {
      id: '/analyses/$analysisId/clusters'
      path: '/clusters'
      fullPath: '/analyses/$analysisId/clusters'
      preLoaderRoute: typeof AnalysesAnalysisIdClustersRouteImport
      parentRoute: typeof AnalysesAnalysisIdRouteRoute
    }
  }
}

interface AnalysesAnalysisIdRouteRouteChildren {
  AnalysesAnalysisIdClustersRoute: typeof AnalysesAnalysisIdClustersRoute
  AnalysesAnalysisIdReviewsRoute: typeof AnalysesAnalysisIdReviewsRoute
  AnalysesAnalysisIdIndexRoute: typeof AnalysesAnalysisIdIndexRoute
}

const AnalysesAnalysisIdRouteRouteChildren: AnalysesAnalysisIdRouteRouteChildren =
  {
    AnalysesAnalysisIdClustersRoute: AnalysesAnalysisIdClustersRoute,
    AnalysesAnalysisIdReviewsRoute: AnalysesAnalysisIdReviewsRoute,
    AnalysesAnalysisIdIndexRoute: AnalysesAnalysisIdIndexRoute,
  }

const AnalysesAnalysisIdRouteRouteWithChildren =
  AnalysesAnalysisIdRouteRoute._addFileChildren(
    AnalysesAnalysisIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysesAnalysisIdRouteRoute: AnalysesAnalysisIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
